version: "3"
services:
  apache:
    build:
      context: "."
      dockerfile: "Dockerfile-${PHP_VERSION}"
      args:
        - "SERVER_ROOT=${SERVER_ROOT}"
        - "PHP_VERSION=${PHP_VERSION}"
        - "DISPLAY_PHPERROR=${DISPLAY_PHPERROR}"
        - "MONGODB_VERSION=${MONGODB_VERSION}"
        - "DB_NAME=${DB_NAME}"
        - "DB_USER=${DB_USER}"
        - "DB_PASSWORD=${DB_PASSWORD}"
    volumes:
      - "${APP_CODE_PATH_HOST}:${APP_CODE_PATH_NGINX}${APP_CODE_CONTAINER_FLAG}"
    ports:
      - "${APACHE_HOST_HTTP_PORT}:80"
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      - "MYSQL_DATABASE=${DB_NAME}"
      - "MYSQL_USER=${DB_USER}"
      - "MYSQL_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}"
    volumes:
      - "${DATA_PATH_HOST}/mysql:/var/lib/mysql"
    ports:
      - "${MYSQL_PORT}:3306"
volumes: {}